apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notification.fullname" . }}
  labels:
    {{- include "notification.labels" . | nindent 4 }}
data:
  KAFKA_SERVER: {{ .Values.config.kafka_server | quote }}