version: '3.8'

services:

  db:
    image: postgres:15
    container_name: db_container
    environment:
      - POSTGRES_DB=test-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  config-server:
    build: ./config-server
    container_name: config-server_container
    ports:
      - "8888:8888"

  gateway:
    build: ./gateway
    container_name: gateway_container
    ports:
      - "8000:8000"
    depends_on:
      - config-server
    environment:
      - CONFIG_SERVER=http://host.docker.internal:8888

  accounts:
    build: ./accounts
    container_name: accounts_container
    ports:
      - "8010:8010"
    depends_on:
      - db
      - config-server
    environment:
      - CONFIG_SERVER=http://host.docker.internal:8888

  exchange-generator:
    build: ./exchange-generator
    container_name: exchange-generator_container
    ports:
      - "8020:8020"
    depends_on:
      - config-server
    environment:
      - CONFIG_SERVER=http://host.docker.internal:8888

  exchange:
    build: ./exchange
    container_name: exchange_container
    ports:
      - "8030:8030"
    depends_on:
      - db
      - config-server
    environment:
      - CONFIG_SERVER=http://host.docker.internal:8888

  transfer:
    build: ./transfer
    container_name: transfer_container
    ports:
      - "8040:8040"
    depends_on:
      - db
      - config-server
    environment:
      - CONFIG_SERVER=http://host.docker.internal:8888

  front-ui:
    build: ./front-ui
    container_name: front-ui_container
    ports:
      - "8080:8080"
    depends_on:
      - config-server
    environment:
      - CONFIG_SERVER=http://host.docker.internal:8888


#KEYCLOAK
  postgres:
    image: postgres:15
    container_name: bankapp-keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: bankapp-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    command:
      - start-dev
    ports:
      - "8085:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - keycloak-network

volumes:
  postgres_data:
    name: keycloak_postgres_data

networks:
  keycloak-network:
    name: keycloak-network