version: '3.8'

services:

  accounts:
    build: ./accounts
    image: accounts

  exchange-generator:
    build: ./exchange-generator
    image: exchange-generator

  exchange:
    build: ./exchange
    image: exchange

  transfer:
    build: ./transfer
    image: transfer

  cash:
    build: ./cash
    image: cash

  front-ui:
    build: ./front-ui
    image: front

  notification:
    build: ./notification
    image: notification