server:
  port: 8040

spring:
  application:
    name: bankapp-transfer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
        registration:
          bankapp-transfer:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: bankapp-transfer
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: profile
            clientAuthenticationMethod: client_secret_post

gateway: ${GATEWAY_URL}

resource:
  alias:
    exchange: /exchange
    accounts: /accounts