server:
  port: 8060

spring:

  application:
    name: notification

  sql:
    init:
      mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

  mail:
    host: smtp.gmail.com
    port: 587
    username: bankapp-email@gmail.com
    password: bankapp-password
    properties.mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        ssl:
          trust: smtp.gmail.com

# Spring Boot Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
