server:
  port: 8060

spring:

  application:
    name: notification

  sql:
    init:
      mode: always

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVER} #localhost:9092
      group-id: bankapp-notification-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: ru.yandex.practicum.dto

  mail:
    host: smtp.gmail.com
    port: 587
    username: bankapp-email@gmail.com
    password: bankapp-password
    properties.mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        ssl:
          trust: smtp.gmail.com

topic:
  notification: notification

# Spring Boot Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
