server:
  port: 8000
spring:
  application:
    name: bankapp-gateway
  config:
    import: configserver:${CONFIG_SERVER}
  cloud:
    discovery:
      client:
        simple:
          instances:
            bankapp-accounts:
              - uri: ${ACCOUNTS_URI}
            bankapp-exchange-generator:
              - uri: ${EXCHANGE_GENERATOR_URI}
            bankapp-exchange:
              - uri: ${EXCHANGE_URI}
            bankapp-transfer:
              - uri: ${TRANSFER_URI}
            bankapp-cash:
              - uri: ${CASH_URI}
    gateway:
      mvc:
        routes:
          - id: accounts-route  # ID роута
            uri: lb://bankapp-accounts  # URI микросервиса, на который следует перенаправлять запрос
            predicates:
              - Path=/accounts/** # URI поступающего в гейтвей запроса, которому матчится роут
            filters:
              - RewritePath=/accounts/?(?<segment>.*), /$\{segment} # фильтр, модифицирующий запрос к целевому сервису (убирается имя сервиса в начале)
          - id: exchange-generator-route  # ID роута
            uri: lb://bankapp-exchange-generator  # URI микросервиса, на который следует перенаправлять запрос
            predicates:
              - Path=/exchange-generator/** # URI поступающего в гейтвей запроса, которому матчится роут
            filters:
              - RewritePath=/exchange-generator/?(?<segment>.*), /$\{segment}
          - id: exchange-route  # ID роута
            uri: lb://bankapp-exchange  # URI микросервиса, на который следует перенаправлять запрос
            predicates:
              - Path=/exchange/** # URI поступающего в гейтвей запроса, которому матчится роут
            filters:
              - RewritePath=/exchange/?(?<segment>.*), /$\{segment}
          - id: transfer-route  # ID роута
            uri: lb://bankapp-transfer  # URI микросервиса, на который следует перенаправлять запрос
            predicates:
              - Path=/transfer/** # URI поступающего в гейтвей запроса, которому матчится роут
            filters:
              - RewritePath=/transfer/?(?<segment>.*), /$\{segment}
          - id: cash-route  # ID роута
            uri: lb://bankapp-cash  # URI микросервиса, на который следует перенаправлять запрос
            predicates:
              - Path=/cash/** # URI поступающего в гейтвей запроса, которому матчится роут
            filters:
              - RewritePath=/cash/?(?<segment>.*), /$\{segment}