server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    discovery:
      client:
        simple:
          instances:
            accounts:
              - uri: ${ACCOUNTS_URI}
            exchange-generator:
              - uri: ${EXCHANGE_GENERATOR_URI}
            exchange:
              - uri: ${EXCHANGE_URI}
            transfer:
              - uri: ${TRANSFER_URI}
            cash:
              - uri: ${CASH_URI}
            notification:
              - uri: ${NOTIFICATION_URI}
    gateway:
      mvc:
        routes:
          - id: accounts-route  # ID роута
            uri: lb://accounts  # URI микросервиса, на который следует перенаправлять запрос
            predicates:
              - Path=/accounts/** # URI поступающего в гейтвей запроса, которому матчится роут
            filters:
              - RewritePath=/accounts/?(?<segment>.*), /$\{segment} # фильтр, модифицирующий запрос к целевому сервису (убирается имя сервиса в начале)
          - id: exchange-generator-route  # ID роута
            uri: lb://exchange-generator  # URI микросервиса, на который следует перенаправлять запрос
            predicates:
              - Path=/exchange-generator/** # URI поступающего в гейтвей запроса, которому матчится роут
            filters:
              - RewritePath=/exchange-generator/?(?<segment>.*), /$\{segment}
          - id: exchange-route  # ID роута
            uri: lb://exchange  # URI микросервиса, на который следует перенаправлять запрос
            predicates:
              - Path=/exchange/** # URI поступающего в гейтвей запроса, которому матчится роут
            filters:
              - RewritePath=/exchange/?(?<segment>.*), /$\{segment}
          - id: transfer-route  # ID роута
            uri: lb://transfer  # URI микросервиса, на который следует перенаправлять запрос
            predicates:
              - Path=/transfer/** # URI поступающего в гейтвей запроса, которому матчится роут
            filters:
              - RewritePath=/transfer/?(?<segment>.*), /$\{segment}
          - id: cash-route  # ID роута
            uri: lb://cash  # URI микросервиса, на который следует перенаправлять запрос
            predicates:
              - Path=/cash/** # URI поступающего в гейтвей запроса, которому матчится роут
            filters:
              - RewritePath=/cash/?(?<segment>.*), /$\{segment}
          - id: notification-route  # ID роута
            uri: lb://notification  # URI микросервиса, на который следует перенаправлять запрос
            predicates:
              - Path=/notification/** # URI поступающего в гейтвей запроса, которому матчится роут
            filters:
              - RewritePath=/notification/?(?<segment>.*), /$\{segment}