server:
  port: 8010

spring:

  application:
    name: accounts

  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
