server:
  port: 8010

spring:
  application:
    name: bankapp-accounts
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
