SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/test-db
SPRING_DATASOURCE_USER=postgres
SPRING_DATASOURCE_PASSWORD=iamroot

JWT_ISSUER_URI=http://localhost:8085/realms/master

MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://localhost:9411/api/v2/spans