server:
  port: 8010

spring:

  application:
    name: bankapp-accounts

  config:
    import: configserver:http://127.0.0.1:8888
  profiles:
    active: local

  sql:
    init:
      mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
