drop table if exists users cascade;
drop table if exists accounts cascade;
drop table if exists userAccounts cascade;

CREATE TABLE IF NOT EXISTS users (

    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email           VARCHAR(255) NOT NULL,
    first_name      VARCHAR(255) NOT NULL,
    last_name       VARCHAR(255) NOT NULL,
    birth_date      TIMESTAMP,
    password        VARCHAR(255) NOT NULL,
    is_deleted      BOOLEAN NOT NULL,

    CONSTRAINT      pk_user PRIMARY KEY (id),

    CONSTRAINT      UQ_USER_NAME UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS accounts (

    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    balance         DOUBLE NOT NULL,
    currency        VARCHAR(255) NOT NULL,
    is_deleted      BOOLEAN NOT NULL,

    CONSTRAINT      pk_item PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS userAccounts (

    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT NOT NULL,
    account_id      BIGINT NOT NULL,
    is_deleted      BOOLEAN NOT NULL,

    CONSTRAINT      pk_cart PRIMARY KEY (id),

    CONSTRAINT  fk_user_account_user_id
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT  fk_user_account_account_id
        FOREIGN KEY (account_id)
            REFERENCES accounts (id)
            ON DELETE CASCADE
    );