drop table if exists users cascade;
drop table if exists accounts cascade;
drop table if exists user_accounts cascade;
drop table if exists roles cascade;

CREATE TABLE IF NOT EXISTS users
(

    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    birth_date TIMESTAMP,
    password   VARCHAR(255)                            NOT NULL,
    is_deleted BOOLEAN                                 NOT NULL,

    CONSTRAINT pk_user PRIMARY KEY (id),

    CONSTRAINT UQ_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS accounts
(

    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value          DECIMAL                                 NOT NULL,
    currency_title VARCHAR(255)                            NOT NULL,
    is_deleted     BOOLEAN                                 NOT NULL,

    CONSTRAINT pk_account PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_accounts
(

    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    account_id BIGINT                                  NOT NULL,
    is_deleted BOOLEAN                                 NOT NULL,

    CONSTRAINT pk_user_account PRIMARY KEY (id),

    CONSTRAINT fk_user_account_user_id
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_user_account_account_id
        FOREIGN KEY (account_id)
            REFERENCES accounts (id)
            ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS roles
(

    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    role_name VARCHAR(255)                            NOT NULL,

    CONSTRAINT pk_role PRIMARY KEY (id),

    CONSTRAINT fk_role_user_id
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE
);