server:
  port: 8080

spring:
  application:
    name: bankapp-front

  config:
    import: configserver:http://127.0.0.1:8888

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
        registration:
          bankapp-front:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: bankapp-front
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: profile
            clientAuthenticationMethod: client_secret_post

gateway: ${GATEWAY_URL}

resource:
  alias:
    accounts: /accounts
    exchange-generator: /exchange-generator
    transfer: /transfer