server:
  port: 8080

spring:
  application:
    name: front

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
        registration:
          bankapp-front:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: bankapp-front
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: profile
            clientAuthenticationMethod: client_secret_post

gateway: ${GATEWAY_URL}

resource:
  alias:
    accounts: bankapp-accounts:8010
    exchange-generator: bankapp-exchange-generator:8020
    transfer: transfer
    cash: cash

# Spring Boot Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true