server:
  port: 8080

spring:
  application:
    name: front

gateway: ${GATEWAY_URL}

resource:
  alias:
    accounts: bankapp-accounts:8010
    exchange-generator: bankapp-exchange-generator:8020
    transfer: transfer
    cash: cash

# Spring Boot Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true