server:
  port: 8000

spring:
  application:
    name: bankapp-front


  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
        registration:
          bankapp-front:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: bankapp-front
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: profile
            clientAuthenticationMethod: client_secret_post

resource:
  server: accounts