server:
  port: 8020

spring:
  application:
    name: exchange-generator

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER} #localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

topic:
  rates: rates

# Spring Boot Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT} # Эндпойнт Zipkin для приема спанов
  tracing:
    sampling:
      probability: 1 # Сэмплируем все запросы