server:
  port: 8020

spring:
  application:
    name: bankapp-exchange-generator
  config:
    import: configserver:http://127.0.0.1:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}