global:
  zipkinUrlGlobal: "http://my-bankapp-zipkin:9411"
  keycloakGlobal: "http://my-bankapp-keycloak:8085/realms/master"
  kafkaServerGlobal: "http://my-bankapp-kafka:9092"

accounts:
  replicaCount: 1
  image:
    repository: accounts 
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8010
  ingress:
    enabled: true
    className: "nginx" 
    hosts:
      - host: accounts 
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    database_url: "jdbc:postgresql://{{ .Release.Name }}-accounts-db:5432/accountsdb"
    database_username: "accounts_user"
    jwt_issuer_uri: "http://my-bankapp-keycloak:8085/realms/master"
    MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: zipkinUrlGlobal

front:
  replicaCount: 1
  image:
    repository: front 
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080 
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: front
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    GATEWAY_URL: "http://"
    KEYCLOAK_ISSUER_URI: keycloakGlobal
    KEYCLOAK_CLIENT_SECRET: "d3qytkUb62j7F85l85YZ9c96exiPljQr"
    KAFKA_SERVER: kafkaServerGlobal
    MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: zipkinUrlGlobal

exchange-generator:
  replicaCount: 1
  image:
    repository: exchange-generator 
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8020 
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: exchange-generator
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    kafka_server: kafkaServerGlobal
    MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: zipkinUrlGlobal

exchange:
  replicaCount: 1
  image:
    repository: exchange 
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8030
  ingress:
    enabled: true
    className: "nginx" 
    hosts:
      - host: exchange 
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    database_url: "jdbc:postgresql://{{ .Release.Name }}-exchange-db:5432/exchangedb"
    database_username: "exchange_user"
    jwt_issuer_uri: keycloakGlobal
    kafka_server: kafkaServerGlobal
    MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: zipkinUrlGlobal

notification:
  replicaCount: 1
  image:
    repository: notification 
    tag: "latest"
    pullPolicy: IfNotPresent 
    MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: zipkinUrlGlobal
  service:
    type: ClusterIP
    port: 8060 
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: notification
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    kafka_server: kafkaServerGlobal
    MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: zipkinUrlGlobal

accounts-db:
  enabled: true
  auth:
    database: accountsdb
    username: accounts_user
    password: "changeM3accounts!" 
  primary:
    persistence:
      enabled: true
      size: 1Gi 

exchange-db:
  enabled: true
  
  auth:
    database: exchangedb
    username: exchange_user
    password: "changeM3exchange!" 
  primary:
    persistence:
      enabled: true
      size: 1Gi 

keycloak:
  auth:
    adminUser: admin
    adminPassword: admin
  postgresql:
    enabled: true
    auth:
      username: hn_keycloak
      password: bn_Kkeycloak
      database: bitnami_keycloak
  extraEnvVars:
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: admin
    - name: KEYCLOAK_EXTRA_ARGS
      value: "--import-realm"
  extraVolumes:
    - name: realm-config
      configMap:
        name: bankapp-realm-configmap
  extraVolumeMounts:
    - name: realm-config
      mountPath: /opt/bitnami/keycloak/data/import
      readOnly: true

kafka:
  enabled: true
  controller:
    replicaCount: 1
  brokers: 1
  listeners:
    client:
      protocol: PLAINTEXT
  auth:
    clientProtocol: PLAINTEXT
    interBrokerProtocol: PLAINTEXT
  zookeeper:
    enabled: true
    replicaCount: 1

zipkin:
  enabled: true
  service:
    type: ClusterIP
    port: 9411
  storage:
    type: mem
  replicaCount: 1

prometheus:
  namespaceOverride: monitoring
  crds:
    create: true