server:
  port: 8888
spring:
  application:
    name: bankapp-config-server
  profiles:
    active: native # Профиль native необходимо включать для поддержки хранилища в локальной файловой системе
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/
