server:
  port: 8030

spring:

  application:
    name: exchange

  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVER} #localhost:9092
      group-id: bankapp-exchange-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: ru.yandex.practicum.dto

logging.level.org.apache.kafka.clients.NetworkClient: ERROR